export type Lyric = {
  text: string;
  duration: number; // ms
};

export const LYRICS: Lyric[] = [
  { text: "", duration: 0 },
  { text: "All I know is now 알게 됐어 나 (I know)", duration: 3000 },
  { text: "그동안 맨날 always up and down (no more)", duration: 3000 },
  { text: "생각 또 생각 spinnin' 'round and 'round, changing my mind", duration: 4000 },
  { text: "수상해서 그렇지 이런 헛소리 (no more)", duration: 3000 },
  { text: "How it's supposed to be 그만해 'cause it's clear", duration: 3000 },
  { text: "(It's simple) it's like biting an apple", duration: 2000 },
  { text: "Toxic lover, you're no better", duration: 3000 },
  { text: "거기 숨지 말고 얼른 나와", duration: 3000 },
  { text: "You, little demon in my storyline, don't knock on my door, I'll see you out", duration: 5000 },
  { text: "And don't you know how sweet it tastes? (How sweet it tastes)", duration: 3000 },
  { text: "Yeah, don't you know how sweet it tastes? (How sweet it tastes)", duration: 3000 },
  { text: "Yeah, don't you know how sweet it tastes, now that I'm without you?", duration: 4000 },
  { text: "나 더는 묻지 않을래 (how sweet it tastes)", duration: 3000 },
  { text: "알려주지 않아도 돼 (how sweet it tastes)", duration: 3000 },
  { text: "Wow, don't you know how sweet it tastes, now that I'm without you?", duration: 4000 },
  { text: "모든 게 typical, so I've been praying so hard for a miracle", duration: 4000 },
  { text: "부르고 있어 나의 이름을 더는 안 봐 drama it's good karma", duration: 4000 },
  { text: "Done scrolling thousand times", duration: 3000 },
  { text: "다 알고 있어 뻔한 수작일 뿐이야", duration: 3000 },
  { text: "완전 쉬운 공식이야, it's like biting an apple", duration: 3000 },
  { text: "And don't you know how sweet it tastes? (How sweet it tastes)", duration: 3000 },
  { text: "Yeah, don't you know how sweet it tastes? (How sweet it tastes)", duration: 3000 },
  { text: "Yeah, don't you know how sweet it tastes, now that I'm without you?", duration: 4000 },
  { text: "나 더는 묻지 않을래 (how sweet it tastes)", duration: 3000 },
  { text: "알려주지 않아도 돼 (how sweet it tastes)", duration: 3000 },
  { text: "Wow, don't you know how sweet it tastes, now that I'm without you?", duration: 4000 },
  { text: "I won't wait, I'm feeling", duration: 3000 },
  { text: "My own way, I'm in it", duration: 3000 },
  { text: "'Cause me and you are different", duration: 3000 },
  { text: "So I won't stay, I'm leaving", duration: 3000 },
  { text: "I won't wait, I'm feeling", duration: 3000 },
  { text: "My own way, I'm in it", duration: 3000 },
  { text: "'Cause me and you are different", duration: 3000 },
  { text: "So I won't stay, I'm leaving", duration: 3000 },
  { text: "And don't you know how sweet it tastes? (How sweet it tastes)", duration: 3000 },
  { text: "Yeah, don't you know how sweet it tastes? (How sweet it tastes)", duration: 3000 },
  { text: "Yeah, don't you know how sweet it tastes, now that I'm without you?", duration: 4000 },
  { text: "나 더는 묻지 않을래 (how sweet it tastes)", duration: 3000 },
  { text: "알려주지 않아도 돼 (how sweet it tastes)", duration: 3000 },
  { text: "Wow, don't you know how sweet it tastes, now that I'm without you?", duration: 4000 },
  { text: "Toxic lover, you're no better", duration: 3000 },
  { text: "거기 숨지 말고 빨리 나와", duration: 3000 },
  { text: "You, little demon in my storyline, don't knock on my door, 너 얼른 나가버려", duration: 5000 },
  { text: "Toxic lover, you're no better", duration: 3000 },
  { text: "거기 숨지 말고 얼른 나와", duration: 3000 },
  { text: "You, little demon in my storyline, don't knock on my door, I'll see you out", duration: 5000 },
];
